version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgis/init/:/docker-entrypoint-initdb.d
    networks:
      - gis-net

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.0
    container_name: geoserver
    restart: unless-stopped
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=gates123
      - PROXY_BASE_URL=https://c220g2-011025.wisc.cloudlab.us/geoserver
    volumes:
      - gsdata:/opt/geoserver_data
    networks:
      - gis-net
    ports:
      - "8080:8080"
    depends_on:
      - postgis

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/html:/usr/share/nginx/html:ro

    depends_on:
      - geoserver
    networks:
      - gis-net
      
volumes:
  pgdata:
  gsdata:
  certbot-etc:
  certbot-var:
  webroot:


networks:
  gis-net:
    driver: bridge

